madmin/urls.py
from django.conf.urls import url
from .views import CustomerListView, CustomerCreateView, CustomerUpdateView, \
    DriverListView, DriverCreateView, DriverUpdateView, UserLocationListView, \
    UserLocationCreateView, UserLocationUpdateView, StoreListView, StoreCreateView, \
    StoreUpdateView, BankListView, BankCreateView, BankUpdateView, AllOrderListView, \
    OrderCreateView, OrderUpdateView, StoreItemListView, StoreItemCreateView, \
    StoreItemUpdateView, StoreBranchCreateView, StoreBranchListView, StoreBranchUpdateView, \
    StoreOwnerListView, StoreOwnerCreateView, StoreOwnerUpdateView, PendingOrderListView, \
    track_order, assign_driver, DriverEvaluationListView, update_order_status, OrderDetailView, \
    BankAccountListView, BankAccountCreateView, BankAccountUpdateView, track_driver, \
    StoreTypeCreateView, StoreTypeListView, StoreTypeUpdateView, PaymentMethodCreateView, \
    PaymentMethodListView, PaymentMethodUpdateView, hidden_driver_evaluation, \
    send_mass_notifications, AppSettingCreateView, AppSettingListView, AppSettingUpdateView, \
    user_balance, StorePhotoListView, StorePhotoCreateView, StorePhotoUpdateView, \
    approve_unapprove_store_photo, fav_unfav_store_items, store_create, user_details, \
    delete_entry, DistrictCreatView, DistrictListView, DistrictUpdateView, \
    madmin_home, store_owner_form, store_owner_details, store_details, delete_all_devices

urlpatterns = [

    url(r'^$', madmin_home, name='madmin_home'),
    url(r'^delete_devices$', delete_all_devices, name='delete_devices'),

    url(r'^store/details$', store_details, name='store_details'),
    url(r'^details$', user_details, name='user_details'),
    url(r'^delete$', delete_entry, name='delete_entry'),

    url(r'^driver/list$', DriverListView.as_view(), name='driver_list'),
    url(r'^driver/create$', DriverCreateView.as_view(), name='driver_create'),
    url(r'^driver/update/(?P<pk>\d+)$', DriverUpdateView.as_view(), name='driver_update'),

    url(r'^notify/all$', send_mass_notifications, name='notify_all'),
    url(r'^driver/track$', track_driver, name='track_driver'),
    url(r'^driver/review/(?P<driver>\d+)$', hidden_driver_evaluation, name='hidden_driver_evaluation'),

    url(r'^order/list$', AllOrderListView.as_view(), name='order_list'),
    url(r'^order/track$', track_order, name='track_order'),
    url(r'^order/assign$', assign_driver, name='assign_driver'),
    url(r'^order/update-status$', update_order_status, name='update_order_status'),
    url(r'^order/list/pending$', PendingOrderListView.as_view(), name='pending_order_list'),
    url(r'^order/create$', OrderCreateView.as_view(), name='order_create'),
    url(r'^order/update/(?P<pk>\d+)$', OrderUpdateView.as_view(), name='order_update'),
    url(r'^order/detail/(?P<pk>\d+)$', OrderDetailView.as_view(), name='order_detail'),

    url(r'^driver-evaluation/list$', DriverEvaluationListView.as_view(), name='driver_evaluation_list'),

    url(r'^customer/list$', CustomerListView.as_view(), name='customer_list'),
    url(r'^customer/create$', CustomerCreateView.as_view(), name='customer_create'),
    url(r'^customer/update/(?P<pk>\d+)$', CustomerUpdateView.as_view(), name='customer_update'),

    url(r'^user/balance$', user_balance, name='user_balance'),
    url(r'^user-location/list$', UserLocationListView.as_view(), name='user_location_list'),
    url(r'^user-location/create$', UserLocationCreateView.as_view(), name='user_location_create'),
    url(r'^user-location/update/(?P<pk>\d+)$', UserLocationUpdateView.as_view(), name='user_location_update'),

    url(r'^store/list$', StoreListView.as_view(), name='store_list'),
    url(r'^store/create$', store_create, name='store_create'),
    url(r'^store/ownerform$', store_owner_form, name='store_owner_form'),
    url(r'^store/update/(?P<pk>\d+)$', StoreUpdateView.as_view(), name='store_update'),

    url(r'^bank/list$', BankListView.as_view(), name='bank_list'),
    url(r'^bank/create$', BankCreateView.as_view(), name='bank_create'),
    url(r'^bank/update/(?P<pk>\d+)$', BankUpdateView.as_view(), name='bank_update'),

    url(r'^district/list$', DistrictListView.as_view(), name='district_list'),
    url(r'^district/create$', DistrictCreatView.as_view(), name='district_create'),
    url(r'^district/update/(?P<pk>\d+)$', DistrictUpdateView.as_view(), name='district_update'),

    url(r'^app-setting/list$', AppSettingListView.as_view(), name='app_setting_list'),
    url(r'^app-setting/create$', AppSettingCreateView.as_view(), name='app_setting_create'),
    url(r'^app-setting/update/(?P<pk>\d+)$', AppSettingUpdateView.as_view(), name='app_setting_update'),

    url(r'^store-type/list$', StoreTypeListView.as_view(), name='store_type_list'),
    url(r'^store-type/create$', StoreTypeCreateView.as_view(), name='store_type_create'),
    url(r'^store-type/update/(?P<pk>\d+)$', StoreTypeUpdateView.as_view(), name='store_type_update'),

    url(r'^payment-method/list$', PaymentMethodListView.as_view(), name='payment_method_list'),
    url(r'^payment-method/create$', PaymentMethodCreateView.as_view(), name='payment_method_create'),
    url(r'^payment-method/update/(?P<pk>\d+)$', PaymentMethodUpdateView.as_view(), name='payment_method_update'),

    url(r'^bank-account/list$', BankAccountListView.as_view(), name='bank_account_list'),
    url(r'^bank-account/create$', BankAccountCreateView.as_view(), name='bank_account_create'),
    url(r'^bank-account/update/(?P<pk>\d+)$', BankAccountUpdateView.as_view(), name='bank_account_update'),

    url(r'^store-photo/fav$', fav_unfav_store_items, name='store_item_fav'),
    url(r'^store-item/list$', StoreItemListView.as_view(), name='store_item_list'),
    url(r'^store-item/create$', StoreItemCreateView.as_view(), name='store_item_create'),
    url(r'^store-item/update/(?P<pk>\d+)$', StoreItemUpdateView.as_view(), name='store_item_update'),

    url(r'^store-branch/list$', StoreBranchListView.as_view(), name='store_branch_list'),
    url(r'^store-branch/create$', StoreBranchCreateView.as_view(), name='store_branch_create'),
    url(r'^store-branch/update/(?P<pk>\d+)$', StoreBranchUpdateView.as_view(), name='store_branch_update'),

    url(r'^store-owner/list$', StoreOwnerListView.as_view(), name='store_owner_list'),
    url(r'^store-owner/create$', StoreOwnerCreateView.as_view(), name='store_owner_create'),
    url(r'^store-owner/update/(?P<pk>\d+)$', StoreOwnerUpdateView.as_view(), name='store_owner_update'),

    url(r'^store-photo/approve$', approve_unapprove_store_photo, name='store_photo_approve'),
    url(r'^store-photo/list$', StorePhotoListView.as_view(), name='store_photo_list'),
    url(r'^store-photo/create$', StorePhotoCreateView.as_view(), name='store_photo_create'),
    url(r'^store-photo/update/(?P<pk>\d+)$', StorePhotoUpdateView.as_view(), name='store_photo_update'),

]

mobilebooking/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from api.views import router, UpdateOrderStatus, TrackOrder, SearchView, StatsView, MarkNotificationsRead

admin.site.site_header = "Dev2you Admin"

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(router.urls)),
    url(r'^api/update-order/', UpdateOrderStatus.as_view()),
    url(r'^api/track-order/', TrackOrder.as_view()),
    url(r'^api/search/', SearchView.as_view()),
    url(r'^api/stats/', StatsView.as_view()),
    url(r'^api/notifications/mark-read/', MarkNotificationsRead.as_view()),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^auth/', include('djoser.urls')),
    url(r'^madmin/', include('madmin.urls', namespace='madmin')),
]

api/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg, Sum
from push_notifications.models import APNSDevice, GCMDevice
from django.conf import settings


class SocialToken(models.Model):
    user = models.ForeignKey(User)
    service_name = models.CharField("Service Name", max_length=10)
    profile_id = models.CharField("Profile ID", max_length=60)
    access_token = models.CharField("Access Token", max_length=250)


class Customer(User):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    gender = models.CharField("Gender", max_length=1, choices=GENDER_CHOICES, default='M')
    loyalty_amount = models.FloatField("Loyalty Amount", default=0.00)
    deposit_amount = models.FloatField("Deposit Amount", default=0.00)

    photo = models.ImageField("Photo", blank=True, null=True, upload_to="photos")

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def avg_rating(self):
        feedbacks = CustomerEvaluation.objects.all().filter(customer=self).aggregate(Avg('rating'))
        return feedbacks['rating__avg']

    class Meta:
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


class Driver(User):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
    notes = models.TextField(null=True, blank=True)
    gender = models.CharField("Gender", max_length=1, choices=GENDER_CHOICES, default='M', null=True, blank=True)
    photo = models.ImageField("Photo", blank=True, null=True, upload_to="photos")

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def avg_rating(self):
        feedbacks = DriverEvaluation.objects.all().filter(driver=self).aggregate(Avg('rating'))
        return feedbacks['rating__avg']

    def is_available(self):
        orders = Order.objects.filter(driver=self).exclude(status__in=['DELIV', 'MCL', 'UCAN', 'MREJ'])
        if len(orders) > 0:
            return False
        else:
            return True

    class Meta:
        verbose_name = 'Driver'
        verbose_name_plural = 'Drivers'


class HiddenDriverEvaluation(models.Model):
    driver = models.ForeignKey(Driver)
    message = models.CharField("Message", max_length=250, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class District(models.Model):
    name = models.CharField("Name", max_length=250)

    def __unicode__(self):
        return self.name


class UserLocation(models.Model):
    user = models.ForeignKey(Customer, related_name='locations')
    name = models.CharField("Name", max_length=250)
    district = models.ForeignKey(District, null=True, blank=True)
    phone = models.CharField("Phone", max_length=250)
    street = models.TextField("Street", null=True, blank=True)
    house_no = models.CharField("House No", max_length=250, null=True, blank=True)
    door_no = models.CharField("Door No", max_length=250, null=True, blank=True)
    door_color = models.CharField("Door Color", max_length=250, null=True, blank=True)
    note = models.TextField("Note", null=True, blank=True)
    longitude = models.CharField("Long", max_length=35)
    latitude = models.CharField("Lat", max_length=35)
    own_location = models.BooleanField("Own Location?", default=True)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)


class StoreType(models.Model):
    name = models.CharField("Store Type", max_length=200)

    def __unicode__(self):
        return self.name


class Store(models.Model):
    name = models.CharField("Store Name", max_length=250)
    thumb = models.ImageField("Thumbnail", null=True, blank=True)

    description = models.TextField("Description", default="N/A")
    avg_time_spent = models.IntegerField("Average Time Spent (Minutes)", default=5)
    store_type = models.ForeignKey(StoreType)
    favorite = models.BooleanField("Favorite", default=False)

    delivery_charge = models.FloatField("Delivery Charge", default=0.0)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def store_balance(self):
        user_balance = UserBalance.objects.all().filter(store=self).aggregate(balance=Sum('amount'))
        return user_balance['balance']

    def thumb_url(self):
        return '%s%s' % (settings.BASE_URL, self.thumb.url)

    def avg_rating(self):
        feedbacks = StoreEvaluation.objects.all().filter(store=self).aggregate(Avg('rating'))
        return feedbacks['rating__avg']

    def __unicode__(self):
        return u"{} - {}".format(self.id, self.name)


class StorePhoto(models.Model):
    store = models.ForeignKey(Store)
    photo = models.ImageField("Store Photo", upload_to="store_photos")
    approved = models.BooleanField("Is approved?", default=False)


class StoreOwner(models.Model):
    customer = models.ForeignKey(Customer)
    store = models.ForeignKey(Store)
    is_active = models.BooleanField("Is Active?", default=True)


class StoreItem(models.Model):
    store = models.ForeignKey(Store, related_name="items")
    name = models.CharField("Item name", max_length=100)
    description = models.TextField("Description")
    photo = models.ImageField("Photo")
    price = models.FloatField("Price")
    favorite = models.BooleanField("Favorite", default=False)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def __unicode__(self):
        return u"{} - {} ".format(self.store.name, self.name)

    def delivery_charge(self):
        return self.store.delivery_charge

    def store_name(self):
        return self.store.name

    def photo_url(self):
        return '%s%s' % (settings.BASE_URL, self.photo.url)

    def avg_rating(self):
        feedbacks = ItemEvaluation.objects.all().filter(item=self).aggregate(Avg('rating'))
        return feedbacks['rating__avg']


class StoreBranch(models.Model):
    store = models.ForeignKey(Store, related_name="branches")
    branch_name = models.CharField("Branch Name", max_length=250)
    district = models.ForeignKey(District, null=True, blank=True)
    phone = models.CharField("Phone", max_length=250)
    longitude = models.CharField("Long", max_length=35)
    latitude = models.CharField("Lat", max_length=35)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def __unicode__(self):
        return u"{} - {} ".format(self.store.name, self.name)


class Bank(models.Model):
    name = models.CharField("Bank Name", max_length=150)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def __unicode__(self):
        return u"{} ".format(self.name)


class BankAccount(models.Model):
    bank = models.ForeignKey(Bank)
    user = models.ForeignKey(User)

    account_no = models.CharField("Account No", max_length=250)
    branch = models.CharField("Branch", max_length=20)

    def __unicode__(self):
        return u"{} {} {}".format(self.bank.name, self.user.username, self.account_no)


class PaymentMethod(models.Model):
    name = models.CharField("Name", max_length=100)
    enabled = models.BooleanField("Is enabled?", default=True)


class Order(models.Model):
    STATUS_CHOICES = (
        ('REQ', u'طلب جديد'),
        ('REV', u'مراجعة'),
        ('APPR', u'معتمد'),
        ('AD', u'مسند إلى المندوب'),
        ('DOTW', u'المندوب في الطريق'),
        ('DIS', u'المندوب في المتجر'),
        ('DLS', u'المندوب غادر المتجر'),
        ('DELIV', u'تم التوصيل'),
        ('MCL', u'مغلق من المشرف'),
        ('UCAN', u'ملغي من العميل'),
        ('MREJ', u'طلب مرفوض')

    )

    PAYMENT_CHOICES = (
        ('COD', 'Cash On Delivery'),
        ('PBC', 'Pay By Credit'),
        ('PBP', 'Pay By Points'),
        ('BT', 'Bank Transfer'),
        ('SPAN', 'Saudi Payment Network')
    )

    user = models.ForeignKey(User)
    driver = models.ForeignKey(Driver, related_name='driver', blank=True, null=True)
    status = models.CharField("Status", max_length=5, choices=STATUS_CHOICES)
    pickup = models.DateTimeField("Requested Pickup Time", null=True, blank=True)
    pickedup = models.DateTimeField("Pickup Time", null=True, blank=True)
    payment_method = models.ForeignKey(PaymentMethod)
    additional_notes = models.TextField(null=True, blank=True)
    total = models.FloatField("Total")
    user_location = models.ForeignKey(UserLocation)
    user_type = models.CharField("User Type", max_length=30)
    paid = models.BooleanField("Paid?", default=True)

    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    def __str__(self):
        return "Order: {}".format(self.id)

    def get_store(self):
        items = self.purchasedstoreitem_set.all()
        if len(items) > 0:
            item = items[0]
            return item.store_item.store
        else:
            return None

    def avg_rating(self):
        feedbacks = OrderEvaluation.objects.all().filter(order=self).aggregate(Avg('rating'))
        return feedbacks['rating__avg']

    def location(self):
        return self.user_location

    def set_store_id(self, store_id):
        self.store_id = store_id

    def display_id(self):
        order = self
        date = order.created_at.date()
        return "{}{}{}{:06}".format(date.year, date.month, date.day, order.id)

    def get_items(self):
        if hasattr(self, 'store_id'):

madmin/models.py
from django.db import models

# Create your models here.

madmin/templates/api/appsetting_form.html
{% extends 'madmin/base.html' %}

{% block page_header %}

    <!-- Start Page Header -->
    <div class="page-header">
        <h1 class="title">App Settings</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'madmin:madmin_home' %}">Admin</a></li>
            <li><a href="{% url 'madmin:app_setting_list' %}">App Setting</a></li>
            <li class="active">Details</li>
        </ol>


    </div>
    <!-- End Page Header -->

{% endblock %}


{% block content %}
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">


            <div class="panel-title">
                App Settings
            </div>

            <form method='post'>

                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }} <br/> {{ field }}
                    </div>

                    <br/>
                {% endfor %}

                <input type='submit'>

            </form>


        </div>
    </div>
    <!-- End Panel -->
{% endblock %}

madmin/templates/api/customer_list.html
{% extends 'madmin/base.html' %}

{% block page_header %}

    <!-- Start Page Header -->
    <div class="page-header">
        <h1 class="title">Customer List</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'madmin:madmin_home' %}">Admin</a></li>
            <li><a href="{% url 'madmin:customer_list' %}">Customers</a></li>
            <li class="active">List</li>
        </ol>

        <!-- Start Page Header Right Div -->
        <div class="right">
            <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'madmin:customer_create' %}" class="btn btn-light">Create</a>
            </div>
        </div>
        <!-- End Page Header Right Div -->

    </div>
    <!-- End Page Header -->

{% endblock %}


{% block content %}
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">

            <!--
            <div class="panel-title">
                Customers List
            </div> -->

            <div class="panel-body table-responsive">
                <!-- The customers list will be displayed here! -->

                <div style="float: right; padding-top: 0">
                    <form id="search" class="searchform">
                        <input type="text" name="query" class="searchbox" style="border: 1px solid #BDC4C9;"
                               id="searchbox" placeholder="Search">
                        <span class="searchbutton"><i onclick="search()" class="fa fa-search"></i></span>
                    </form>
                </div>
                <br/>
                <br/>
                <br/>

                <table class="table table-striped">

                    <thead>
                    <tr>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=first_name">Name</a></td>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=username">Username</a></td>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=email">Email</a></td>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=gender">Gender</a></td>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=loyalty_amount">Loyalty Amount</a></td>
                        <td><a href="{% url 'madmin:customer_list' %}?sort=deposit_amount">Deposit Amount</a></td>
                        <td>Action</td>
                    </tr>
                    </thead>

                    <tbody>

                    {% for customer in customer_list %}

                        <tr>
                            <td><b>{{ customer.first_name }} {{ customer.last_name }}</b></td>
                            <td><b>{{ customer.username }}</b></td>
                            <td>{{ customer.email }}</td>
                            <td>{{ customer.get_gender_display }}</td>
                            <td>{{ customer.loyalty_amount }} <span>ر.س </span></td>
                            <td>{{ customer.deposit_amount }} <span>ر.س </span></td>
                            <td>
                                <a href="{% url 'madmin:user_details' %}?user={{ customer.id }}">
                                    Details
                                </a> |

                                <a href="{% url 'madmin:customer_update' customer.id %}">Edit</a> |
                                <a href="{% url 'madmin:user_balance' %}?user={{ customer.id }}">Balance</a> |
                                <a href="{% url 'madmin:delete_entry' %}?model=Customer&pk={{ customer.id }}">Delete</a>
                            </td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>
            </div>

            <!---- PAGINATION ------>

            <div style="text-align: center;">
                <nav>
                    <ul class="pagination pagination-lg">

                        {% if page_obj.has_previous %}

                            <li>
                                <a href="{% url 'madmin:customer_list' %}?page={{ page_obj.previous_page_number }}&query={{ query }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                        {% endif %}

                        {% for page_no in paginator.page_range %}
                            <li {% if page_no == page_obj.number %} class="active" {% endif %}>
                                <a href="{% url 'madmin:customer_list' %}?page={{ page_no }}&query={{ query }}">{{ page_no }}</a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}

                            <li>
                                <a href="{% url 'madmin:customer_list' %}?page={{ page_obj.next_page_number }}&query={{ query }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>

                        {% endif %}

                    </ul>

                </nav>
            </div>

            <!---- END PAGINATION ------>

        </div>
    </div>
    <!-- End Panel -->
{% endblock %}

madmin/templates/api/driver_list.html
{% extends 'madmin/base.html' %}

{% block page_header %}

    <!-- Start Page Header -->
    <div class="page-header">
        <h1 class="title">Driver List</h1>
        <ol class="breadcrumb">
            <li><a href="{% url 'madmin:madmin_home' %}">Admin</a></li>
            <li><a href="{% url 'madmin:driver_list' %}">Drivers</a></li>
            <li class="active">List</li>
        </ol>

        <!-- Start Page Header Right Div -->
        <div class="right">
            <div class="btn-group" role="group" aria-label="...">
                <a href="{% url 'madmin:driver_create' %}" class="btn btn-light">Create</a>
            </div>
        </div>
        <!-- End Page Header Right Div -->

    </div>
    <!-- End Page Header -->

{% endblock %}


{% block content %}
    <!-- Start Panel -->
    <div class="col-md-12">
        <div class="panel panel-default">

            <!--
            <div class="panel-title">
                drivers List
            </div> -->

            <div class="panel-body table-responsive">

                <div style="float: right; padding-top: 0">
                    <form id="search" class="searchform">
                        <input type="text" name="query" class="searchbox" style="border: 1px solid #BDC4C9;"
                               id="searchbox" placeholder="Search">
                        <span class="searchbutton"><i onclick="search()" class="fa fa-search"></i></span>
                    </form>
                </div>
                <br/>
                <br/>
                <br/>


                <table class="table table-striped">

                    <thead>
                    <tr>
                        <td><a href="{% url 'madmin:driver_list' %}?sort=id">User ID</a></td>
                        <td><a href="{% url 'madmin:driver_list' %}?sort=username">Username</a></td>
                        <td><a href="{% url 'madmin:driver_list' %}?sort=first_name">Full Name</a></td>
                        <td>Available?</td>
                        <td>Action</td>
                    </tr>
                    </thead>

                    <tbody>

                    {% for driver in driver_list %}

                        <tr>
                            <td>{{ driver.id }}</td>
                            <td><b>{{ driver.username }}</b></td>
                            <td>{{ driver.first_name }} {{ driver.last_name }}</td>
                            <td>
                                {% if driver.is_available %}
                                    <span class="fa fa-check">&nbsp;</span>
                                {% else %}
                                    <span class="fa fa-close">&nbsp;</span>
                                {% endif %}
                            </td>

                            <td style="font-size: 10px ">
                                <a class="btn btn-default" href="{% url 'madmin:user_balance' %}?user={{ driver.id }}">
                                    <span class="fa fa-dollar"> Balance</span>
                                </a>

                                <a class="btn btn-default" href="{% url 'madmin:user_details' %}?user={{ driver.id }}">
                                    <span class="fa fa-user"> Details</span>
                                </a>


                                <a class="btn btn-default" href="{% url 'madmin:driver_update' driver.id %}">
                                    <span class="fa fa-edit"> Update</span>
                                </a>

                                <a class="btn btn-default" href="{% url 'madmin:order_list' %}?driver={{ driver.id }}">
                                    <span class="fa fa-cab"> Orders</span>
                                </a>

                                <br/> <br/>
                                <a class="btn btn-default"
                                   href="{% url 'madmin:driver_evaluation_list' %}?driver={{ driver.id }}">
                                    <span class="fa fa-bullhorn"> Feedback</span>
                                </a>

                                <a class="btn btn-default"
                                   href="{% url 'madmin:track_driver' %}?driver={{ driver.id }}">
                                    <span class="fa fa-map-marker"> Track</span>
                                </a>

                                <br/> <br/>
                                <a class="btn btn-default" href="{% url 'madmin:hidden_driver_evaluation' driver.id %}">
                                    <span class="fa fa-gavel"> Hidden Feedback</span>
                                </a>


                                <a class="btn btn-default"
                                   href="{% url 'madmin:delete_entry' %}?model=Driver&pk={{ driver.id }}">
                                    <span class="fa fa-close">Delete</span>
                                </a>

                            </td>
                        </tr>



                    {% endfor %}

                    </tbody>
                </table>
            </div>


            <!---- PAGINATION ------>


            <div style="text-align: center;">
                <nav>
                    <ul class="pagination pagination-lg">

                        {% if page_obj.has_previous %}

                            <li>
                                <a href="{% url 'madmin:driver_list' %}?page={{ page_obj.previous_page_number }}&query={{ query }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                        {% endif %}


                        {% for page_no in paginator.page_range %}

                            <li {% if page_no == page_obj.number %} class="active" {% endif %}><a
                                    href="{% url 'madmin:driver_list' %}?page={{ page_no }}&query={{ query }}">{{ page_no }}</a>
                            </li>
                        {% endfor %}

                        {% if page_obj.has_next %}

                            <li>
                                <a href="{% url 'madmin:driver_list' %}?page={{ page_obj.next_page_number }}&query={{ query }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>

                        {% endif %}

                    </ul>
                </nav>
            </div>

            <!---- END PAGINATION ------>

        </div>
    </div>
    <!-- End Panel -->
{% endblock %}